# Generated by Django 5.1.3 on 2024-11-13 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_antiderivative_user_antiderivativefilled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilledAntiderivative',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latexText', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilledConstant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('value', models.FloatField()),
                ('filledAntiderivative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.filledantiderivative')),
            ],
        ),
        migrations.DeleteModel(
            name='AntiderivativeFilled',
        ),
    ]
