# Generated by Django 5.1.3 on 2024-11-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_latextext_antiderivative_inputlatex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constant',
            name='value',
        ),
        migrations.DeleteModel(
            name='FilledConstant',
        ),
    ]
